# Generated by Django 5.0.3 on 2024-03-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0003_perfilusuario_tokenverificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
